### ISSUE TITLE
[German] Hintergrundbild Windows PC

### ISSUE THREAD

**Issue by ToxicStoxm** [hannescam/Flappy-Hero#1]
Beim pc ist das Hintergrundbild im Vollbildmodus nur im linken oberen Eck zu sehen und der rest ist schwarz.

**Comment by hannescam** [comment]
es sollte gelöst sein aber du musst es selbst kompilieren (du brauchst make und g++) und du must dir die sdl2 dll dateien kopieren
wenn es das problem löst dann bitte schließ dieses issue

**Comment by hannescam** [comment]
@ToxicStoxm hat es das problem gelöst?

**Comment by ToxicStoxm** [comment]
Ja
